from __future__ import annotations

import re
import unittest
from pathlib import Path


class VersionHistoryTests(unittest.TestCase):
    def test_complete_history_is_preserved_and_new_releases_are_appended(self) -> None:
        path = Path(__file__).resolve().parents[1] / "version.txt"
        text = path.read_text(encoding="utf-8")
        versions = re.findall(r"(?m)^v(\d+)\b", text)
        self.assertGreater(len(versions), 100)
        self.assertIn("1898", versions)
        self.assertEqual(
            versions[-27:],
            ["6016", "6017", "6018", "6019", "6020", "6021", "6022", "6023", "6024", "6025", "6026", "6027", "6028", "6029", "6030", "6031", "6032", "6033", "6034", "6035", "6036", "6037", "6038", "6039", "6040", "6041", "6042"],
        )
        self.assertIn("v5091 - 2026-07-20", text)
        self.assertIn("v5092 - 2026-07-20", text)
        self.assertIn("v5093 - 2026-07-20", text)
        self.assertIn("Restored the complete version.txt development history", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5092.", text)
        self.assertIn("Removed three later search_tracks function definitions", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5093.", text)
        self.assertIn("v5094 - 2026-07-20", text)
        self.assertIn("Removed all remaining database upgrade ALTER TABLE branches", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5094.", text)
        self.assertIn("v5095 - 2026-07-20", text)
        self.assertIn("v5096 - 2026-07-20", text)
        self.assertIn("Reused an already confirmed native inactive-deck preload", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5095.", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5096.", text)
        self.assertIn("v5097 - 2026-07-20", text)
        self.assertIn("Removed four additional write-only Python A/B runtime fields", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5097.", text)
        self.assertIn("v5098 - 2026-07-20", text)
        self.assertIn("Moved process-wide native audio-engine runtime ownership", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5098.", text)
        self.assertIn("v5099 - 2026-07-20", text)
        self.assertIn("Moved native lifecycle subscription, event routing, ordered track_started dispatch and deduplication", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5099.", text)
        self.assertIn("v5100 - 2026-07-20", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5100.", text)
        self.assertIn("v5101 - 2026-07-20", text)
        self.assertIn("Moved station-local queue, history, runtime playback state and rotation cursor persistence", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5101.", text)
        self.assertIn("v5102 - 2026-07-20", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5102.", text)
        self.assertIn("v6000 - 2026-07-20", text)
        self.assertIn("direct FFmpeg 7.1.5 libavformat", text)
        self.assertIn("Preserved the external SoundSolution ssproc DSP", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6000.", text)
        self.assertIn("v6001 - 2026-07-20", text)
        self.assertIn("canonical Ice-Audio-Info source header", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6001.", text)
        self.assertIn("v6002 - 2026-07-21", text)
        self.assertIn("Removed the legacy DEBUG=1 and WEB_BROADCASTER_DEBUG runtime modes", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6002.", text)
        self.assertIn("v6003 - 2026-07-21", text)
        self.assertIn("tolerant of isolated AVERROR_INVALIDDATA failures", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6003.", text)
        self.assertIn("v6004 - 2026-07-21", text)
        self.assertIn("Ice-Bitrate, Ice-Description, Ice-Genre and Ice-URL", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6004.", text)
        self.assertIn("v6005 - 2026-07-21", text)
        self.assertIn("Removed the optional User-Agent header", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6005.", text)
        self.assertIn("v6006 - 2026-07-21", text)
        self.assertIn("Removed the obsolete crossfade_ms setting", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6006.", text)
        self.assertIn("v6007 - 2026-07-21", text)
        self.assertIn("newly created Autostart encoders start immediately", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6007.", text)
        self.assertIn("v6008 - 2026-07-22", text)
        self.assertIn("individual stream branches can be attached and detached", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6008.", text)
        self.assertIn("v6009 - 2026-07-22", text)
        self.assertIn("live dry-to-DSP and DSP-to-dry PCM source selector", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6009.", text)
        self.assertIn("v6010 - 2026-07-22", text)
        self.assertIn("without requiring Save settings", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6010.", text)
        self.assertIn("v6011 - 2026-07-22", text)
        self.assertIn("Reduced normal console startup output", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6011.", text)
        self.assertIn("v6012 - 2026-07-22", text)
        self.assertIn("bundled native Linux SoundSolution v0.5.0 runtime", text)
        self.assertIn("ssnative-process-raw <config.dat> 2 44100", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6012.", text)
        self.assertIn("v6013 - 2026-07-22", text)
        self.assertIn("Integrated SoundSolution Native v0.5.0 directly", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6013.", text)
        self.assertIn("v6014 - 2026-07-23", text)
        self.assertIn("vanished HTTP clients", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6014.", text)
        self.assertIn("v6015 - 2026-07-23", text)
        self.assertIn("one central `DEBUG` environment switch", text)
        self.assertIn("without enabling Flask debug mode", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6015.", text)
        self.assertIn("v6016 - 2026-07-23", text)
        self.assertIn("without hiding genuine failures", text)
        self.assertIn("native daemon version to 6016", text)
        self.assertIn("v6017 - 2026-07-25", text)
        self.assertIn("scheduled station scripts from interrupting", text)
        self.assertIn("native daemon version to 6017", text)
        self.assertIn("v6018 - 2026-07-25", text)
        self.assertIn("canonical marker", text)
        self.assertIn("native daemon version to 6018", text)
        self.assertIn("v6019 - 2026-07-25", text)
        self.assertIn("native daemon version to 6019", text)
        self.assertIn("v6020 - 2026-07-25", text)
        self.assertIn("native daemon version to 6020", text)
        self.assertIn("v6021 - 2026-07-26", text)
        self.assertIn("native daemon version to 6021", text)
        self.assertIn("v6022 - 2026-07-28", text)
        self.assertIn("SoundSolution Native v6.1.0 x86-64 SSE2-direct", text)
        self.assertIn("native daemon version to 6022", text)
        self.assertIn("v6023 - 2026-07-28", text)
        self.assertIn("consolidated web asset tree", text)
        self.assertIn("native daemon version to 6023", text)
        self.assertIn("v6024 - 2026-07-28", text)
        self.assertIn("self-contained Web Broadcaster buildkit", text)
        self.assertIn("byte-for-byte unchanged", text)
        self.assertIn("native daemon version to 6024", text)
        self.assertIn("v6025 - 2026-08-11", text)
        self.assertIn("monotonic `performance.now()` playback anchor", text)
        self.assertIn("100 ms", text)
        self.assertIn("native daemon version to 6025", text)
        self.assertIn("v6026 - 2026-08-11", text)
        self.assertIn("crossed hammer and screwdriver", text)
        self.assertIn("15x15 px", text)
        self.assertIn("native daemon version to 6026", text)
        self.assertIn("v6027 - 2026-08-11", text)
        self.assertIn("all six obsolete SVG icon assets", text)
        self.assertIn("now-empty html/static/icons directory", text)
        self.assertIn("native daemon version to 6027", text)
        self.assertIn("v6028 - 2026-08-13", text)
        self.assertIn("deny-by-default authentication", text)
        self.assertIn("one-time setup token", text)
        self.assertIn("Cheroot WSGI server", text)
        self.assertIn("native daemon version to 6028", text)
        self.assertIn("v6029 - 2026-08-13", text)
        self.assertIn("nginx reverse-proxy deployment guide", text)
        self.assertIn("Certbot", text)
        self.assertIn("native daemon version to 6029", text)
        self.assertIn("v6030 - 2026-08-13", text)
        self.assertIn("trusted LAN-only operation", text)
        self.assertIn("nginx, a domain name, Certbot or TLS", text)
        self.assertIn("native daemon version to 6030", text)
        self.assertIn("v6031 - 2026-08-13", text)
        self.assertIn("full regression suite", text)
        self.assertIn("v6032 - 2026-08-13", text)
        self.assertIn("v6033 - 2026-08-13", text)
        self.assertIn("v6034 - 2026-08-13", text)
        self.assertIn("v6035 - 2026-08-13", text)
        self.assertIn("v6036 - 2026-08-13", text)
        self.assertIn("v6037 - 2026-08-13", text)
        self.assertIn("v6038 - 2026-08-14", text)
        self.assertIn("v6039 - 2026-08-14", text)
        self.assertIn("v6040 - 2026-08-14", text)
        self.assertIn("v6041 - 2026-08-14", text)
        self.assertIn("v6042 - 2026-08-16", text)
        self.assertIn("malformed ID3 metadata console filtering", text)
        self.assertIn("TENC, TCOP and TOPE", text)
        self.assertIn("actual FFmpeg 7.1.5 ID3 parser", text)
        self.assertIn("malformed TCON genre-frame noise", text)
        self.assertIn("condition-based playback progress", text)
        self.assertIn("routing exceptions", text)
        self.assertIn("untrusted Host requests return the intended HTTP 400", text)
        self.assertIn("protocol readiness", text)
        self.assertIn("stable on-air encoder baseline", text)
        self.assertIn("embedded artist/title tags", text)
        self.assertIn("terminal native_audio_probe_eof event", text)
        self.assertIn("live pytest progress", text)


if __name__ == "__main__":
    unittest.main()
