from __future__ import annotations

import re
import unittest
from pathlib import Path


class VersionHistoryTests(unittest.TestCase):
    def test_complete_history_is_preserved_and_new_releases_are_appended(self) -> None:
        path = Path(__file__).resolve().parents[1] / "version.txt"
        text = path.read_text(encoding="utf-8")
        versions = re.findall(r"(?m)^v(\d+)\b", text)
        self.assertGreater(len(versions), 100)
        self.assertIn("1898", versions)
        app_text = (path.parent / "app.py").read_text(encoding="utf-8")
        app_match = re.search(r'(?m)^APP_VERSION = "([0-9]+)"$', app_text)
        self.assertIsNotNone(app_match)
        current_version = int(app_match.group(1))
        self.assertGreaterEqual(current_version, 6021)
        self.assertEqual(versions[-1], str(current_version))
        recent_start = len(versions) - 1 - versions[::-1].index("6021")
        recent_versions = [int(version) for version in versions[recent_start:]]
        self.assertEqual(recent_versions, list(range(6021, current_version + 1)))
        self.assertIn("v5091 - 2026-07-20", text)
        self.assertIn("v5092 - 2026-07-20", text)
        self.assertIn("v5093 - 2026-07-20", text)
        self.assertIn("Restored the complete version.txt development history", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5092.", text)
        self.assertIn("Removed three later search_tracks function definitions", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5093.", text)
        self.assertIn("v5094 - 2026-07-20", text)
        self.assertIn("Removed all remaining database upgrade ALTER TABLE branches", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5094.", text)
        self.assertIn("v5095 - 2026-07-20", text)
        self.assertIn("v5096 - 2026-07-20", text)
        self.assertIn("Reused an already confirmed native inactive-deck preload", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5095.", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5096.", text)
        self.assertIn("v5097 - 2026-07-20", text)
        self.assertIn("Removed four additional write-only Python A/B runtime fields", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5097.", text)
        self.assertIn("v5098 - 2026-07-20", text)
        self.assertIn("Moved process-wide native audio-engine runtime ownership", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5098.", text)
        self.assertIn("v5099 - 2026-07-20", text)
        self.assertIn("Moved native lifecycle subscription, event routing, ordered track_started dispatch and deduplication", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5099.", text)
        self.assertIn("v5100 - 2026-07-20", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5100.", text)
        self.assertIn("v5101 - 2026-07-20", text)
        self.assertIn("Moved station-local queue, history, runtime playback state and rotation cursor persistence", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5101.", text)
        self.assertIn("v5102 - 2026-07-20", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 5102.", text)
        self.assertIn("v6000 - 2026-07-20", text)
        self.assertIn("direct FFmpeg 7.1.5 libavformat", text)
        self.assertIn("Preserved the external SoundSolution ssproc DSP", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6000.", text)
        self.assertIn("v6001 - 2026-07-20", text)
        self.assertIn("canonical Ice-Audio-Info source header", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6001.", text)
        self.assertIn("v6002 - 2026-07-21", text)
        self.assertIn("Removed the legacy DEBUG=1 and WEB_BROADCASTER_DEBUG runtime modes", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6002.", text)
        self.assertIn("v6003 - 2026-07-21", text)
        self.assertIn("tolerant of isolated AVERROR_INVALIDDATA failures", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6003.", text)
        self.assertIn("v6004 - 2026-07-21", text)
        self.assertIn("Ice-Bitrate, Ice-Description, Ice-Genre and Ice-URL", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6004.", text)
        self.assertIn("v6005 - 2026-07-21", text)
        self.assertIn("Removed the optional User-Agent header", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6005.", text)
        self.assertIn("v6006 - 2026-07-21", text)
        self.assertIn("Removed the obsolete crossfade_ms setting", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6006.", text)
        self.assertIn("v6007 - 2026-07-21", text)
        self.assertIn("newly created Autostart encoders start immediately", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6007.", text)
        self.assertIn("v6008 - 2026-07-22", text)
        self.assertIn("individual stream branches can be attached and detached", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6008.", text)
        self.assertIn("v6009 - 2026-07-22", text)
        self.assertIn("live dry-to-DSP and DSP-to-dry PCM source selector", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6009.", text)
        self.assertIn("v6010 - 2026-07-22", text)
        self.assertIn("without requiring Save settings", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6010.", text)
        self.assertIn("v6011 - 2026-07-22", text)
        self.assertIn("Reduced normal console startup output", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6011.", text)
        self.assertIn("v6012 - 2026-07-22", text)
        self.assertIn("bundled native Linux SoundSolution v0.5.0 runtime", text)
        self.assertIn("ssnative-process-raw <config.dat> 2 44100", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6012.", text)
        self.assertIn("v6013 - 2026-07-22", text)
        self.assertIn("Integrated SoundSolution Native v0.5.0 directly", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6013.", text)
        self.assertIn("v6014 - 2026-07-23", text)
        self.assertIn("vanished HTTP clients", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6014.", text)
        self.assertIn("v6015 - 2026-07-23", text)
        self.assertIn("one central `DEBUG` environment switch", text)
        self.assertIn("without enabling Flask debug mode", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6015.", text)
        self.assertIn("v6016 - 2026-07-23", text)
        self.assertIn("without hiding genuine failures", text)
        self.assertIn("native daemon version to 6016", text)
        self.assertIn("v6017 - 2026-07-25", text)
        self.assertIn("scheduled station scripts from interrupting", text)
        self.assertIn("native daemon version to 6017", text)
        self.assertIn("v6018 - 2026-07-25", text)
        self.assertIn("canonical marker", text)
        self.assertIn("native daemon version to 6018", text)
        self.assertIn("v6019 - 2026-07-25", text)
        self.assertIn("native daemon version to 6019", text)
        self.assertIn("v6020 - 2026-07-25", text)
        self.assertIn("native daemon version to 6020", text)
        self.assertIn("v6021 - 2026-07-26", text)
        self.assertIn("native daemon version to 6021", text)
        self.assertIn("v6022 - 2026-07-28", text)
        self.assertIn("SoundSolution Native v6.1.0 x86-64 SSE2-direct", text)
        self.assertIn("native daemon version to 6022", text)
        self.assertIn("v6023 - 2026-07-28", text)
        self.assertIn("consolidated web asset tree", text)
        self.assertIn("native daemon version to 6023", text)
        self.assertIn("v6024 - 2026-07-28", text)
        self.assertIn("self-contained Web Broadcaster buildkit", text)
        self.assertIn("byte-for-byte unchanged", text)
        self.assertIn("native daemon version to 6024", text)
        self.assertIn("v6025 - 2026-08-11", text)
        self.assertIn("monotonic `performance.now()` playback anchor", text)
        self.assertIn("100 ms", text)
        self.assertIn("native daemon version to 6025", text)
        self.assertIn("v6026 - 2026-08-11", text)
        self.assertIn("crossed hammer and screwdriver", text)
        self.assertIn("15x15 px", text)
        self.assertIn("native daemon version to 6026", text)
        self.assertIn("v6027 - 2026-08-11", text)
        self.assertIn("all six obsolete SVG icon assets", text)
        self.assertIn("now-empty html/static/icons directory", text)
        self.assertIn("native daemon version to 6027", text)
        self.assertIn("v6028 - 2026-08-13", text)
        self.assertIn("deny-by-default authentication", text)
        self.assertIn("one-time setup token", text)
        self.assertIn("Cheroot WSGI server", text)
        self.assertIn("native daemon version to 6028", text)
        self.assertIn("v6029 - 2026-08-13", text)
        self.assertIn("nginx reverse-proxy deployment guide", text)
        self.assertIn("Certbot", text)
        self.assertIn("native daemon version to 6029", text)
        self.assertIn("v6030 - 2026-08-13", text)
        self.assertIn("trusted LAN-only operation", text)
        self.assertIn("nginx, a domain name, Certbot or TLS", text)
        self.assertIn("native daemon version to 6030", text)
        self.assertIn("v6031 - 2026-08-13", text)
        self.assertIn("full regression suite", text)
        self.assertIn("v6032 - 2026-08-13", text)
        self.assertIn("v6033 - 2026-08-13", text)
        self.assertIn("v6034 - 2026-08-13", text)
        self.assertIn("v6035 - 2026-08-13", text)
        self.assertIn("v6036 - 2026-08-13", text)
        self.assertIn("v6037 - 2026-08-13", text)
        self.assertIn("v6038 - 2026-08-14", text)
        self.assertIn("v6039 - 2026-08-14", text)
        self.assertIn("v6040 - 2026-08-14", text)
        self.assertIn("v6041 - 2026-08-14", text)
        self.assertIn("v6042 - 2026-08-16", text)
        self.assertIn("v6043 - 2026-08-17", text)
        self.assertIn("v6044 - 2026-08-19", text)
        self.assertIn("v6045 - 2026-08-31", text)
        self.assertIn("v6046 - 2026-08-31", text)
        self.assertIn("v6047 - 2026-08-31", text)
        self.assertIn("first 60 seconds and the final 120 seconds", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6047.", text)
        self.assertIn("v6048 - 2026-09-03", text)
        self.assertIn("Scheduler-origin queue items", text)
        self.assertIn("scheduled-script interruption guard", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6048.", text)
        self.assertIn("v6049 - 2026-09-03", text)
        self.assertIn("physical-file replacement detection", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6049.", text)
        self.assertIn("v6050 - 2026-09-04", text)
        self.assertIn("native next-track recovery", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6050.", text)
        self.assertIn("v6051 - 2026-09-04", text)
        self.assertIn("station worker", text.lower())
        self.assertIn("DEBUG=1", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6051.", text)
        self.assertIn("v6052 - 2026-09-04", text)
        self.assertIn("malformed audio frames", text)
        self.assertIn("skip-required", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6052.", text)
        self.assertIn("v6053 - 2026-09-05", text)
        self.assertIn("release version synchronization regression", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6053.", text)
        self.assertIn("v6054 - 2026-09-05", text)
        self.assertIn("encoder START lifecycle", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6054.", text)
        self.assertIn("v6055 - 2026-09-05", text)
        self.assertIn("short-track lifecycle race", text)
        self.assertIn("terminal, consumed", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6055.", text)
        self.assertIn("v6056 - 2026-09-05", text)
        self.assertIn("need-next load storm", text)
        self.assertIn("active deck", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6056.", text)
        self.assertIn("recoverable MP3 frame diagnostics", text)
        self.assertIn("bootstrap detail", text)
        self.assertIn("native_long_track_fallback", text)
        self.assertIn("malformed ID3 metadata console filtering", text)
        self.assertIn("buffered Cheroot response writer", text)
        self.assertIn("IOBase.__del__", text)
        self.assertIn("TENC, TCOP and TOPE", text)
        self.assertIn("`LYRICIST`, `MIXARTIST` and `INVOLVEDPEOPLE`", text)
        self.assertIn("actual FFmpeg 7.1.5 ID3 parser", text)
        self.assertIn("malformed TCON genre-frame noise", text)
        self.assertIn("condition-based playback progress", text)
        self.assertIn("routing exceptions", text)
        self.assertIn("untrusted Host requests return the intended HTTP 400", text)
        self.assertIn("protocol readiness", text)
        self.assertIn("stable on-air encoder baseline", text)
        self.assertIn("embedded artist/title tags", text)
        self.assertIn("terminal native_audio_probe_eof event", text)
        self.assertIn("live pytest progress", text)
        self.assertIn("v6076 - 2026-09-18", text)
        self.assertIn("flaky native audio-probe regression test", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6076.", text)
        self.assertIn("v6077 - 2026-09-18", text)
        self.assertIn("cross-station protected-playback leak", text)
        self.assertIn("Updated APP_VERSION and native daemon version to 6077.", text)


if __name__ == "__main__":
    unittest.main()
